language: java
jdk:
- openjdk11
services:
- docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: EXt1i81jI8JiM2DPPirrV06AF195d/o+ELDPsK0bX8UP23vGIrd2eAogyW95vnrt5XjXB3IRPE6GtSTILcM1BJu5+q+RTEqIPSW94JeXgcQbzNsGqKmrSHgvYIzs03mRmMutZruKrkpF8WrQevlt4cY1F9lyiRrLvm7lykCSW+Hy4fmpHZwyU+FRBJ4IYuFSVkLMMr25G80jzVYv1cCaqmkfrEsDGedUbL2cNBBd6H+fdh3mOWy9JqkpTDPwUIDtsWtUsaqk3EcxNGloJBCHmA8ROnyuYXZG+wEuDkd9VQCaNI4MVHLli+1MUkqjF64RTKAVA5wPTeyye0owSNxsVsr9a2qsEl6d+2cCCdFeLpM5yMGL3xmAzsyCGXI0XhlB4GJ+B/p5YNRAJo8E+72Si40NARylDveMSeZb1glq14sLYK7LSN+jmQXhoD2gDBGat0ry1ouifh4CMOYtVI4gTM0Zak0+VvxcpD8XvVS3VCXs3cY34SrY5HtGCAhRG7yrZmdcr99ZzDhczJ0Qx/+ptkLr3ICpWKpqXeogfV9YN/6wrQeAAQb3iBKjDbdVT40ZFOG37mXYL52oMnJobHbYrR3v/j/d5NYHPu4OLRBRFTKu4StlI55lR8pvbYQUZPGYX/WEU52eqgjhsL0gKCN1Dg1XPrhDEj6LowTzU1wktKA=
  - secure: gzembP7n4vxF+lHE9rCyD0KxyBQnO3q3kakxtqcAuWjq6lO5vQqvqfQ/zDu6GP5IMq6obVH6bfW5vHAL8iTaRA2Gd1iARz7YAGb6OCRYSC8o6JFj/pikKR0AmqJH/MQ5a2oOWZbnux13aQUcFUAp4qxGVdT+wJL1H3OympjiIEaRPqqLE3XfltaiXSxotF4unBE/anFT5EVh2c2U4GxcEgFB9r7hsjko7yrjEZrcRU0uRQmz9uRhAlJE/UTO42R6nWRQXsi77b1diGSZwoae7nHvP0j1c1eE3Iwcumh4SL166utUoez44SSUOZd9ws0VjniNFC/Q49ctTPGgM6Gbtr5CBxcZx5XErTWQGOdBnFKARq+AzusZb9qmxCqjINsq2PLYp6FQr2HGdblvG1COEuCecnHsLiHfEjmL0ju/hXX98gEtyUnGOPEPXjPQu0ALVG3pNyhXKnnNkrb61EF7kvHVwB3kq9X88xL+iXlmOpSXzhUTcIkRa6bbaYGItBWQIqXsqXhN/nxs/2MRehxqqmjq/PNRrvR6iM7Ohgcc6up/i2vxDG79N5B5R4wmCoD2jPgPe2z96ufl0WKK0xH4CxIaJIqZ4kPx9YMzvW/bQJvQnjWEO2JBleaNSglHbwU3F3+z7upKTMAdGOLPDkDuJVm7BfaZooXHIlmSsIKJjxs=
  - secure: JTkT2Q30GXc8NroHXju54c5+wNLhVnrXSHgETdDf1H2lOe0AgEUrHhN4xQRG5clfdRBdPu9vgWalUr7cKRCCvW40VLKDtTUu5MhFaDr7O9837M3QoF7GJzvXZs5Cu4yzzxPg+U77Qs/q+kMIwx7dmmZqMhs8qt3jHUx7G75yTOhuK2VBQ+zIvWrnc9rX942iWVpgJFqaO8l9zS3AI4hqQF50NFb41RtvQ1cw54mfG8eOxBZVwxgATtMaNXn9Qrm0CYO1TI9SuMk7W47vWnQetiDxIJYwidyTCqgRYKo4OjoUiBffdd7Smn6MU6MpRUYv0MaJ/Bm993LGWz4oAPXRmvDCwMwZlBP7NNn/Rj7X0YkHxeKpX3nVpU/VQanp1MGvTAWxGap6+/5kBxt4ZjWclOqq79399fsguBUVJKRQvpwODbvutRAl9kkyfms79YOUe+zDTBWohz4AnNVFVneL6zEAllq8Y6gp70y1C3y31sdQVYG3k1MeTxfBmujZG6065v5Y2TYrTgo1iQyI3TFvaFUd9dlkQPqOKl+EzkWlyVwF35VDqa4lYy8C6CifgXNcn2zgWW3LS9wm7RDj0823PR0vUEFT+MJLnqxzEtIbUQ9YBcB/QydC5UzUYoQHjTQAVmfTExOa55nV+QfSzrgUctbAz+XtmneupOl72/2GSbo=
before_install:
- AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/
  $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
- curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
- sudo apt-get install apt-transport-https
- sudo apt-get update && sudo apt-get install azure-cli
install: true
after_success:
- |-
  set -ex;
  echo "$AZURE_SP_PSW" | docker login ${ACR} -u "$AZURE_APP_ID" --password-stdin && \
  docker build -t "${ACR}/${TRAVIS_COMMIT}" . && \
  docker push "${ACR}/${TRAVIS_COMMIT}"
