language: java

env:
  global:
    secure: cG002e4G6TAuYZ2xSL0Vmz5vvxCir8mUO5jroDBVK424jQiH0DBgSYoLuJyT2dZLDef8w2xIBRDH+KBgiJEi5A8n4iuBi1gUGIbOC2SlsjvDkd8/OrBoPZMN88bKeyyW40uxDaidY7Ln25XFDShzesc2pk37pBgOV+rK3Rgv9JTRth1p61xk/toBSkS9LCV0K8/P+i1qam41eCO2pZloxyPdL57Yn9zyHzT1OGt3y6CGZUInVeCGDiILbjLgUK4lSPYSjfAASaaLa/6FRa5Zrn12/ViBz9o9yn9CbnU+hnYDEPOdBVFYPUdPVaSvcTQs8K7/jOomHdaHHIBjCtZOfvUpAp040ecY9B/VJyFxKdDW+G8SuOhbR7fGbqIHPUAS6y11AgMDfse3ZkN2V6C8ym0c7gqzj0rAEKJ+xajmTUjNdmbO/EMDumdxMwOBmVJ1Vch4u/MP7EJ0Yv6IyfYga6ulHxzjQSDffjtIHEiwgh8utoIEnoQ5JH76hu/HcwsuBm8StcKdEcXACvZdg0WDY6OphXo5nxOUNUbhTx8is6MKXpGpj3v76Ld3E9KJNi8nhoxWb0I2Xf7EH5ZRaoPggcbZa7MmdJKNtQ8A8i+9L94Qg8Lj5ujUKrADgipEP/n1rSN0zWfeIvZ0J4SU2XS/oXnjy7oJGwaLStmkd+Pc4AU=


jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv
  -in google-key.json.enc -out google-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=google-key.json
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
- gcloud components install beta
- export GOOGLE_APPLICATION_CREDENTIALS=./google-key.json


install: true
script:
  - |
    set -ex;
    docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
    docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
    gcloud beta run deploy "${CLOUD_RUN_SERVICE}" \
      --image="${IMAGE}:${TRAVIS_COMMIT}" \
      --platform=managed \
      --region="${CLOUD_RUN_REGION}" \
      --allow-unauthenticated;
    set +x
